# -*- coding: utf-8 -*-
"""2026 Har_standardized

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1doarnrq5eWzgFzmuoF8DeJfbkdAQNtaL
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
print(np.__version__)
print(hasattr(np, '_core'))  # True = numpy 2.0+, False = numpy < 2.0

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Data preparation for HAR dataset
"""

import numpy as np
import pickle

import pandas as pd
from sklearn.preprocessing import StandardScaler

np.random.seed(0)


# replace the dataset path of the folder with your own
dataset_path = '/content/drive/MyDrive/RL-MTL-TL-main/datasets/UCI HAR Dataset/'

x_train = pd.read_csv(dataset_path + 'train/X_train.txt', delimiter=r'\s+', header=None)
y_train = pd.read_csv(dataset_path + 'train/y_train.txt', delimiter=r'\s+', header=None)
subject_train = pd.read_csv(dataset_path + 'train/subject_train.txt', delimiter=r'\s+', header=None)

x_test = pd.read_csv(dataset_path + 'test/X_test.txt', delimiter=r'\s+', header=None)
y_test = pd.read_csv(dataset_path + 'test/y_test.txt', delimiter=r'\s+', header=None)
subject_test = pd.read_csv(dataset_path + 'test/subject_test.txt', delimiter=r'\s+', header=None)

x = np.array(pd.concat([x_train, x_test], ignore_index=True))
y = np.array(pd.concat([y_train, y_test], ignore_index=True)).squeeze()
subject = np.array(pd.concat([subject_train, subject_test], ignore_index=True)).squeeze()

# transform y to 2 classes
y[np.isin(y, [1,2,3,5])] = 0
y[np.isin(y, [4,6])] = 1

# --------------------
# standardize X in each task

x_transformed = np.zeros((x.shape[0], x.shape[1]))
scaler = StandardScaler()
for t in np.unique(subject):
    index = np.where(subject == t)[0]
    x_standardized = scaler.fit_transform(x[index, :])
    x_transformed[index, :] = x_standardized

# save the standardized data to a pickle file
with open('/content/drive/MyDrive/RL-MTL-TL-main/datasets/2026/har_standardized.pkl', 'wb') as f:
    pickle.dump((x_transformed, y, subject), f)

#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Sanity check for har_standardized.pkl
"""

import numpy as np
import pickle

# Load the pickle file
load_path = '/content/drive/MyDrive/RL-MTL-TL-main/datasets/2026/har_standardized.pkl'

with open(load_path, 'rb') as f:
    (x_pca, y, subject) = pickle.load(f)

print("=" * 60)
print("SANITY CHECK FOR har_standardized.pkl")
print("=" * 60)

# Check shapes
print(f"\n1. Data shapes:")
print(f"   x shape: {x_pca.shape}")
print(f"   y shape: {y.shape}")
print(f"   subject shape: {subject.shape}")

# Check y values (CRITICAL)
print(f"\n2. Target variable (y) analysis:")
print(f"   Unique y values: {np.unique(y)}")
print(f"   Number of unique values: {len(np.unique(y))}")
print(f"   Is binary classification? {len(np.unique(y)) == 2}")

# Count each class
print(f"\n3. Class distribution:")
unique, counts = np.unique(y, return_counts=True)
for val, count in zip(unique, counts):
    percentage = count / len(y) * 100
    print(f"   Class {val}: {count} samples ({percentage:.2f}%)")

# Check subject values
print(f"\n4. Subject (task) analysis:")
print(f"   Unique subjects: {np.unique(subject)}")
print(f"   Number of subjects: {len(np.unique(subject))}")

# Check data types
print(f"\n5. Data types:")
print(f"   x dtype: {x_pca.dtype}")
print(f"   y dtype: {y.dtype}")
print(f"   subject dtype: {subject.dtype}")

# Check for NaN or Inf
print(f"\n6. Data quality:")
print(f"   x has NaN: {np.isnan(x_pca).any()}")
print(f"   x has Inf: {np.isinf(x_pca).any()}")
print(f"   y has NaN: {np.isnan(y).any()}")

# Final verdict
print("\n" + "=" * 60)
if len(np.unique(y)) == 2 and set(np.unique(y)) == {0, 1}:
    print("✅ PASS: File is correctly prepared for binary classification")
else:
    print("❌ FAIL: File is NOT binary classification!")
    print(f"   Expected: {{0, 1}}")
    print(f"   Found: {set(np.unique(y))}")
print("=" * 60)